### ISSUE TITLE
Option to use local configuration

### ISSUE THREAD

**Issue by Silthus** [Silthus/chrome-enterprise-tab-rotate#1]
Currently only remote JSON configs are supported. To make full use of the extension it would be useful to configure the complete tab rotation with a local config and provide it via policy.

In the settings GUI the config must be provided in a separate tab as JSON. In the policy it can be configured with separate keys.

The schema would look like this:

```json
{
    "type": "object",
    "properties": {
        "source": {
            "type": "string",
            "title": "Config type.",
            "description": "DIRECT (default) or URL. You can load a config from a URL or use the direct_config section for a direct config."
        },
        "url": {
      "type": "string",
      "title": "Config url.",
      "description": "Provide the url to load your tab rotate config."
    },
    "retry_count": {
        "type": "integer",
        "title": "Retry count (default: 5)",
        "description": "How often should the extension try to load the config until it gives up. -1 for infinite."
    },
    "retry_interval": {
        "type": "integer",
        "title": "Retry interval in seconds (default: 60s)",
        "description": "How long should the extension wait to retry loading the config after an error occured."
    },
    "reload_interval": {
        "type": "integer",
        "title": "Reload interval in seconds (default: 60s)",
        "description": "How often should we reload the config and check if there were any changes."
    },
        "config": {
            "type": "object",
            "title": "Direct config.",
            "description": "You can specify a direct config that is loaded by the plugin. You need to set ConfigType to DIRECT.",
            "properties": {
                "autoStart": {
                    "title": "Autostart tab rotation.",
                    "description": "If set to true the plugin will automatically start rotating the configured tabs when chrome starts.",
                    "type": "boolean"
                },
                "lazyLoadTabs": {
                    "title": "Lazy load tabs.",
                    "description": "If set to true will only load two tabs and the rest async in the background.",
                    "type": "boolean"
                },
                "fullscreen": {
                    "title": "Fullscreen mode.",
                    "description": "If set to true will enter fullscreen after starting.",
                    "type": "boolean"
                },
                "websites": {
                    "type": "array",
                    "id": "ListOfWebsites",
                    "items": {
                        "type": "object",
                        "properties": {
                            "url": {
                                "type": "string"
                            },
                            "duration": {
                                "type": "integer"
                            },
                            "tabReloadIntervalSeconds": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    }
} 
```

//cc @CorCornelisse
//migrated from https://github.com/KevinSheedy/chrome-tab-rotate/pull/44

**Comment by Silthus** [comment]
@CorConelisse I started work on this issue and already implemented the feature to provide a local config via policies. However I did not have the time to test it yet, but if you want you can download the unpacked extension over this link: https://github.com/Silthus/chrome-enterprise-tab-rotate/suites/391603569/artifacts/1025351 and test it.

I will try to proceed with this feature on the weekend.

**Comment by Silthus** [comment]
This feature can be tested using this build: https://github.com/Silthus/chrome-enterprise-tab-rotate/suites/396138851/artifacts/1074765

**Comment by CorCornelisse** [comment]
@Silthus, apologies for the late reply, it took us some time to figure out how to packages the extension into a CRX and get it provisioned to the managed Chromebit. We did succeed there, however we seem to be unable to get it to use the policy we provide it through json.

This could be because we've interpreted the schema wrongly? We've tried the following and checked chrome://policy to see if any of the values were actually being set, but neither chrome://policy nor right-clicking the plugin for settings showed we were able to change any of the defaults:

`{
  "fullscreen": true,
  "autoStart": true,
  "lazyLoadTabs": true,
  "websites": [
    {
      "url": "https://bing.com ",
      "duration": 30,
      "tabReloadIntervalSeconds": 3600
    },
    {
      "url": "https://duckduckgo.com",
      "duration": 30,
      "tabReloadIntervalSeconds": 3600
    },
    {
      "url": "https://google.com",
      "duration": 30,
      "tabReloadIntervalSeconds": 3600
    }
  ]
}`

---

`{
"config": 
{
  "fullscreen": true,
  "autoStart": true,
  "lazyLoadTabs": true,
  "websites": [
    {
      "url": "https://bing.com ",
      "duration": 30,
      "tabReloadIntervalSeconds": 3600
    },
    {
      "url": "https://duckduckgo.com",
      "duration": 30,
      "tabReloadIntervalSeconds": 3600
    },
    {
      "url": "https://google.com",
      "duration": 30,
      "tabReloadIntervalSeconds": 3600
    }
  ]
}
}`

---
{
"properties":
{
"source":"LOCAL",
"retry_count": 60,
"retry_interval": 20,
"reload_interval": 120
}
}

**Comment by Silthus** [comment]
The first option should work (see the example in the updated readme and docs directory.

My guess is the source property. Can you try writing it all in lowercase: `local`

**Comment by Silthus** [comment]
I did some more research and came accross the chromium documentation for configuring policies on ChromeOS: https://www.chromium.org/administrators/configuring-policy-for-extensions

For your use case the following should work:

```json
{
    "source": {
        "Value": "local"
    },
    "config": {
        "Value": {
            "autoStart": {
                "Value": true
            },
            "fullscreen": {
                "Value": true
            },
            "lazyLoadTabs": {
                "Value": true
            },
            "websites": {
                "Value": [
                    {
                        "url": "https://bing.com ",
                        "duration": 30,
                        "tabReloadIntervalSeconds": 3600
                    },
                    {
                        "url": "https://duckduckgo.com",
                        "duration": 30,
                        "tabReloadIntervalSeconds": 3600
                    },
                    {
                        "url": "https://google.com",
                        "duration": 30,
                        "tabReloadIntervalSeconds": 3600
                    }
                ]
            }
        }
    }
}
```

Let me know if this works. If yes I will add some official documentation about this.

**Comment by CorCornelisse** [comment]
This part works:

`{
    "source": {
        "Value": "local"
    }
}`

However, we're not able to set the local config yet. Tried the following mimimal config to work, without result so far.

**Comment by CorCornelisse** [comment]
We're getting somewhere, it looks like the following is being parsed succesfully:
`
{
    "source": {
        "Value": "local"
    },
    "config": {
        "Value": {
            "autoStart": true,
            "fullscreen": true,
            "lazyLoadTabs": true,
			"websites": [
                    {
                        "url": "https://bing.com ",
                        "duration": 30,
                        "tabReloadIntervalSeconds": 3600
                    },
                    {
                        "url": "https://duckduckgo.com",
                        "duration": 30,
                        "tabReloadIntervalSeconds": 3600
                    },
                    {
                        "url": "https://google.com",
                        "duration": 30,
                        "tabReloadIntervalSeconds": 3600
                    }
            ]
    	}          
    }
}
`

**Comment by CorCornelisse** [comment]
However, it won't work immediately.  Looks like we have to hit the "start" button first.

So looks like policy is provided and parsed correctly, but the auto-start isn't triggered yet.

**Comment by CorCornelisse** [comment]
The following might provide some debug hints:

When the extension is installed the first time (completely factory-reset chromebit), and the configuration is provided through policy (automatically happens when it gets installed). If you click "start" it starts with the default policy (not the provided policy). If however, you reboot the device after the installation of the extension and then hit start, it starts with the provided configuration.

**Comment by Silthus** [comment]
Do you have access to the extensions page? If yes can you click on the Backgroundpage link and export the log from the developer console?

https://developer.chrome.com/extensions/tut_debugging#debug_bg

**Comment by Silthus** [comment]
And can you please use the latest build? I added some more debug output so we can better trace whats going on: https://github.com/Silthus/chrome-enterprise-tab-rotate/suites/399655164/artifacts/1111634

**Comment by CorCornelisse** [comment]
You can see in the first screenshot, the config is set to local, and a config is provided.
I've tried reloading the plug-in twice (didn't work ofcourse, cause it wasn't running), followed by hitting start, you'll see it's using the default built-in configuration

![Screenshot 2020-01-14 at 17 31 53](https://user-images.githubusercontent.com/1043904/72366173-0ad9ef00-36fa-11ea-9a12-272d2856bf5b.png)

I've hit stop, followed by start again, to see if this would make a difference, however it still use the default config. Now, I went to options and pressed "save", which triggered loading the provided policy

![Screenshot 2020-01-14 at 17 32 53](https://user-images.githubusercontent.com/1043904/72366185-0f9ea300-36fa-11ea-9eee-b6beb6056b45.png)
![Screenshot 2020-01-14 at 17 33 36](https://user-images.githubusercontent.com/1043904/72366198-11686680-36fa-11ea-96f2-d625bffcb62d.png)

**Comment by CorCornelisse** [comment]
In addition, when the rotation plug-in is running, and we change the policy values, these aren't picked up by the running plug-in until you hit the "save" button. (starting and stopping will keep running on the last "saved" config)

**Comment by Silthus** [comment]
Seems like you found the problem :)

I updated the code so that it reloads the config if the policy changed. Can you test it with the current build please?

https://github.com/Silthus/chrome-enterprise-tab-rotate/suites/401739698/artifacts/1135576

**Comment by CorCornelisse** [comment]
This successfully fixes the configuration change problem. One issue remains though. The plugin isn't started automatically. We still have to hit "Start".

Once the config changes, it reloads, it also calls reload() which throws an error cause the extension wasn't started/running yet.

After rebooting the device, with a configuration that has autostart set to true, it still doesn't autostart:
![Screenshot 2020-01-15 at 12 48 23](https://user-images.githubusercontent.com/1043904/72431640-9eacc900-3795-11ea-9542-42c2471e28fb.png)

**Comment by Silthus** [comment]
Okay I think I found the problem. Can you try with this build please: https://github.com/Silthus/chrome-enterprise-tab-rotate/suites/402137644/artifacts/1139561

**Comment by CorCornelisse** [comment]
That's it, works like a charm now.

We did also test adding more sites through policy while plug-in was running, changing existing sites and removing sites. All worked excellent!

Would you happen to have a timeline on when you're planning to publish the plug-in in store? 

If we can provide any assistance regarding documentation/testing, please let us know.

**Comment by Silthus** [comment]
I am glad it works now :)
I will try to publish the extension this weekend.

Since you asked you actually could help me document your managed chrome os config and what you did to get it to work.

It would be great if you add the documentation as a pull request in the `docs/chromeos.md` file and reference #2
