### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by Silthus** [Silthus/chrome-enterprise-tab-rotate#2]
- [x] configuration documentation
- [x] policy documentation
  - [x] ChromeOS
  - [x] Local
  - [x] Remote
  - [x] Registry
  - [x] GPO
- [x] end user documentation
- [ ] contributing documentation

**Comment by Silthus** [comment]
@CorConelisse the extension is now in the review process and will soon be published.

**Comment by Silthus** [comment]
Just a short update: Google just rejected the publishing of the extension and I need to rework the promotion images...
I will try my best to get this published to the store as soon as possible.

**Comment by CorCornelisse** [comment]
Hi @Silthus, that's a bummer, appreciate the update though!

Let me know if I can be of any assistance.

**Comment by Silthus** [comment]
@CorCornelisse I re-submitted the extension just now. Now I need to wait for the approval and hope the best :)
