### ISSUE TITLE
lazyLoadTabs not followed

### ISSUE THREAD

**Issue by frm1001xplrr** [Silthus/chrome-enterprise-tab-rotate#31]
According to the documentation setting lazyLoadTabs to true will "Open empty tabs and load the website on the first rotation", so i figure setting it to false will "Open all tabs and load websites immediately"

When i run http://weboost.dk/tabcycle.json there is no difference. It always lazy loads. 

Chrome v85.0.4183.121 (Official Build) (64-bit)
Enterprise Tab Rotate v1.1.1

Happy to help in any way.

/frm

**Comment by Silthus** [comment]
Thank you for the bug report, I will look into it shortly.

**Comment by frm1001xplrr** [comment]
Awesome :)  It's such a pleasure with addons that are actively developed. 

/f

**Comment by Silthus** [comment]
I found and fixed both of your bugs. However the automated release is currently broken and I need to look into it.
I will release the bugfixes as soon as the release works.

**Comment by frm1001xplrr** [comment]
Brilliant 🥇 
Very appreciative of your quick effort :)))

/f

**Comment by Silthus** [comment]
Please leave a rating on the chrome store if the extension helps you and you are satisfied with my support :).
That would tremendously help me.

**Comment by frm1001xplrr** [comment]
Absolutely 👍
