### ISSUE TITLE
Options not saved? (or fetching JSON file buggy)

### ISSUE THREAD

**Issue by frm1001xplrr** [Silthus/chrome-enterprise-tab-rotate#32]
We're using your addon to cycle through dashboards in the office, and it's awesome! 

Configuration is user friendly and can be done remotely by anyone from our internal project management system, which webhooks to integromat.com, which produces a JSON file and uploads to ftp, which is fetched by Chrome Enterprise Tab Rotate (CETR)  every XX secs. :) 

We've had issues where the updated JSON file does not trigger an update in CETR.
Loading the JSON file in a browser confirms that the file is updated. 
When looking in CETR settings we noticed that the options were not saved - or perhaps they are not loaded when opening Options a second time? Here's a short screen recording: http://somup.com/cYQUFLljU1

We can't be sure if the Options are not saved, which prevents loading the updated JSON file, or there's a bug with fetching the JSON file, but would be happy to help get rid of the bug in any way we can. 

/f

**Comment by Silthus** [comment]
Can you post me your JSON file that has issues with the update, if possible? You can remove the URLs if they are internal and not meant to be shared.

Also: is the bug reproducible? Does the JSON config fail to update every time?

**Comment by frm1001xplrr** [comment]
>> Can you post me your JSON file that has issues with the update, if possible? 
Sure: http://weboost.dk/tabcycle.json

>> Also: is the bug reproducible? Does the JSON config fail to update every time?
I was screenrecording the bug a few times, after confirming that config failed to update 5 times in a row. Of course, it suddenly works and I'm not able to get it to fail now. I believe what i did was change the remote URL to a file that doesn't exist on the server, and then back to the working one. That seems to have triggered a succesfull sequence of updating...

However, what IS reproducible is this: 
I have several Chrome profiles for different work purposes (bookmarks, addons, settings, etc)
If a Chrome window of any profile is already opened, opening the CETR profile (clean Chrome profile, only CETR addon installed) will not start the tab rotation automatically. 
The addon dropdown status shows "Stop, Pause, Reload" which means it's in status: Start. 
Clicking Pause & Resume does nothing
Clicking Stop closes the window.
Clicking Reload actually start the tab rotation.

We're planning to run 4 different Chrome profiles from the same box Chromecasted to 4 TVs, but this won't be possible at the moment. If the workaround to the original issue (config not updating) works in general, i think this is a worthy issue to take on instead. 
I should probably open a feature request for this though :)

/f
