### ISSUE TITLE
Multiple Instance weird bug

### ISSUE THREAD

**Issue by TnTFreebug** [Silthus/chrome-enterprise-tab-rotate#37]
**Describe the bug**

Running on Google Chrome. : 

I have a little concern, when I use it on 2 instances (one screen portrait mode and the other is landscape).
  So I have 2 jason config file. I start the first rotator under my user profile and 
the second under another user profile (using RunAs).  

Both are running and rotating for 10 minutes and they stop rotating.  
If I clause one of chrome process, the second one can be restarted and work well.  I've try different duration and tab refresgh parameter in the json config without succes.  

It's like timer get confuse event if the running une 2 set of credential.  

Could you try this configuration and try to figure out ?  I can give you the URL of my 2 json config. 

Alone : both of my json config work well.  as soon as second instance running, It just stop rotating after some minutes

**Comment by Silthus** [comment]
Hi thank you for the bug report.

I will try to reproduce the issue locally. Can you send me the link to your JSON files?

You can obfuscate or remove the URLs if you want.

**Comment by TnTFreebug** [comment]
Here my URL : 

Horizontal : https://bit.ly/3mS5RXo
Vertical :  https://bit.ly/37P5sPn

One you get it, i'll remove it at you next post ;-)

thank a lot !

**Comment by TnTFreebug** [comment]
Let me know if i can help or test something !

**Comment by Silthus** [comment]
Thanks for the links. One more question how are your starting your separate processes?

Are they isolated or do you just open a second window and switch the profile?

Can you share the command line arguments for the startup as well?

Thanks!

**Comment by TnTFreebug** [comment]
As I have 2 differents json file (one per screen), I was not able to do it in the config of TabRotator.
So I decide to use a script powershell to launch both instance under different Windows Account.

I use :
start-process chrome.exe  #/(launch Chrome under current user session This one have rotator config 1 vertical screen)

start-process chrome.exe -credential   #/(to launch Chrome under another user Account  This one have TabRotator config 2 horizontal screen) 


Tell me if you are able to reproduce this issue ! Do not hesite for more detail

**Comment by TnTFreebug** [comment]
Were you able to reproduce the problem ?

**Comment by frm1001xplrr** [comment]
I have this exact problem! 
On the same laptop I had 2 Chrome profiles run 2 different JSON configs. After a while both Chrome instances stopped working. If i closed one of the Chrome windows and reloaded the second window, the second would continue to work.
I started the 2 Chrome profiles with the command lines: 
"C:\Program Files\Google\Chrome\Application\chrome.exe" --profile-directory="Default"
"C:\Program Files\Google\Chrome\Application\chrome.exe" --profile-directory="Profile 1"
I never got this to work, so ended up running the 2 Chrome profiles from 2 computers :/
