### ISSUE TITLE
tabReloadIntervalSeconds not working 

### ISSUE THREAD

**Issue by frm1001xplrr** [Silthus/chrome-enterprise-tab-rotate#42]
**Describe the bug**
tabReloadIntervalSeconds is not working/unpredictable. 

**To Reproduce**
1. Run this JSON: tinyurl.com/etb-test
2. Chrome opens 3 tabs and loads them.
3. On the first round every tab will reload when made active.
4. On the second round only the first tab will reload.
5. No tabs ever reload again.
This behavious seems to change with different values of tabReloadIntervalSeconds. 
At one point every tab would reload every time is was made active. 

**Expected behavior**
Tabs reload according to each tabReloadIntervalSeconds value. 

**Desktop (please complete the following information):**
 - OS: Macos Big Sur
 - Browser: Chrome 88 64b

**Additional context**
I have a feeling this bug is what is affecting https://github.com/Silthus/chrome-enterprise-tab-rotate/issues/37 .
I spent hours last October trying to find out why the tabReloadIntervalSeconds stopped working with multiple Chrome profiles/instances.  Perhaps tabReloadIntervalSeconds was just buggy from the start, and multiple profiles was not hte issue?

Thanks for your time and continued efforts on this project, Silthus :)

**Comment by ufwtlsb** [comment]
this.lastReload.add(this.tabReloadIntervalSeconds,"seconds")< moment.utc()
change 
this.lastReload.add(this.tabReloadIntervalSeconds,"seconds")> moment.utc()

**Comment by frm1001xplrr** [comment]
Any chance of progress on this bug? 

We're using the plugin for a status page in the office, showing an Uptimerobot Dashboard and a Google Data Studio dashboard, but neither of the pages update as specified in the json. 

`{
    "websites": [
        {
            "url": "https://datastudio.google.com/embed/reporting/Removed-ID",
            "duration": 30,
            "tabReloadIntervalSeconds": 300,
            "zoom": 1
        },
        {
            "url": "https://stats.uptimerobot.com/Removed-ID",
            "duration": 15,
            "tabReloadIntervalSeconds": 600,
            "zoom": 0.66
        }
    ],
    "autoStart": true,
    "fullscreen": true,
    "lazyLoadTabs": true
}`
