### ISSUE TITLE
This extension violates the Chrome Web Store policy.

### ISSUE THREAD

**Issue by StephenHogan-IBM** [Silthus/chrome-enterprise-tab-rotate#71]
**Describe the bug**
Extension disabled: "This extension violates the Chrome Web Store policy."

**Screenshots**
![image](https://user-images.githubusercontent.com/66841600/166140542-edf84687-4436-4adf-9ce3-32010904c18f.png)

**Desktop (please complete the following information):**
- Microsoft Edge Version 101.0.1210.32 (Official build) (x86_64)
- Enterprise Tab Rotate 1.1.2

**Additional context**
The plugin doesn't appear to be available anymore, but enabling it remediates the issue.
But for how long?

**Comment by Silthus** [comment]
Yes, I got a mail from Google yesterday telling me the extension was removed due to policy violations. They however did not specify what violations.

I will look into it and get the extension relisted as soon as possible.

**Comment by Silthus** [comment]
Here is the excerpt from a mail I missed: 

Item name: Enterprise Tab Rotate

Item ID: phdmnkgnjkbnpmeaodonildfklccgimp

Violation(s):

Use of Permissions:

Violation reference ID: Purple Potassium
Violation: Requesting but not using the following permission(s):
activeTab
How to rectify: Remove the above permission(s)
Relevant section of the program policy:
Request access to the narrowest permissions necessary to implement your Product's features or services. Don't attempt to "future proof" your Product by requesting a permission that might benefit services or features that have not yet been implemented. (learn more)
