### ISSUE TITLE
Chrome Webstore

### ISSUE THREAD

**Issue by JamesMCTB** [Silthus/chrome-enterprise-tab-rotate#86]
This appears to be no longer available at the Chrome webstore here: https://chrome.google.com/webstore/detail/enterprise-tab-rotate/phdmnkgnjkbnpmeaodonildfklccgimp

Can it be reinstated?

**Comment by Silthus** [comment]
Yes I am aware of this and currently trying to get the extension up-to-date to comply with the newest webstore policies.

**Comment by SimFre** [comment]
Are there any updates to this yet?

**Comment by Silthus** [comment]
I am sorry, but I do not have enough time for this project at the moment.
I will archive the project. So feel free to fork and continue it.

Once I get the time I will do a recode of the extension respecting the new chrome webstore policy.
